### ISSUE TITLE
intermittent error: ssh_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/factory#30]
[_setup_forbid-domain-change-WZTZS2RNQ6IUGB2OBL3VBCEYRPWF4IGVVQPNZWPR73YI5WEK2YJQ] Running shell script
        + factory/factory run --image liquid --smp 2 --memory 2048 --share setup:/opt/setup PYTHONUNBUFFERED=yeah /opt/setup/bin/run_first_boot_tests.py
        ...........:)
        ssh_exchange_identification: read: Connection reset by peer
        Traceback (most recent call last):
          File "factory/factory", line 7, in <module>
            factory.main(sys.argv[1:])
          File "/home/jenkins/.jenkins/workspace/_setup_forbid-domain-change-WZTZS2RNQ6IUGB2OBL3VBCEYRPWF4IGVVQPNZWPR73YI5WEK2YJQ/factory/factory.py", line 733, in main
            COMMANDS[options.command](options.platform, *args)
          File "/home/jenkins/.jenkins/workspace/_setup_forbid-domain-change-WZTZS2RNQ6IUGB2OBL3VBCEYRPWF4IGVVQPNZWPR73YI5WEK2YJQ/factory/factory.py", line 469, in run_factory
            vm.ssh(cmd)
          File "/home/jenkins/.jenkins/workspace/_setup_forbid-domain-change-WZTZS2RNQ6IUGB2OBL3VBCEYRPWF4IGVVQPNZWPR73YI5WEK2YJQ/factory/factory.py", line 439, in ssh
            self.invoke_ssh(ssh_command)
          File "/home/jenkins/.jenkins/workspace/_setup_forbid-domain-change-WZTZS2RNQ6IUGB2OBL3VBCEYRPWF4IGVVQPNZWPR73YI5WEK2YJQ/factory/factory.py", line 418, in invoke_ssh
            subprocess.run(cmd, check=True)
          File "/usr/lib/python3.5/subprocess.py", line 708, in run
            output=stdout, stderr=stderr)
        subprocess.CalledProcessError: Command '['ssh', 'liquid-admin@localhost', '-p', '41966', '-o', 'UserKnownHostsFile=known_hosts', '-o', 'StrictHostKeyChecking=no', '-o', 'ConnectTimeout=30', '-o', 'IdentitiesOnly=yes', '-i', 'id_ed25519', 'sudo PYTHONUNBUFFERED=yeah /opt/setup/bin/run_first_boot_tests.py']' returned non-zero exit status 255
        script returned exit code 1

**Comment by mgax** [comment]
Does it happen in other scripts, or is it specific to first-boot tests?

**Comment by mgax** [comment]
I suspect this issue is specific to the Liquid images - they restart sshd on first boot after they generate new server keys. The correct behaviour is to boot with sshd stopped, generate new keys, and then start it. Try this:

* Remove any ssh server keys when building the image. This should keep sshd from starting on first boot.
* Run `dpkg-reconfigure openssh-server` as part of `/etc/rc.local`, here's the one-liner from a digitalocean droplet, it's pretty standard: `test -e /etc/ssh/ssh_host_dsa_key || dpkg-reconfigure openssh-server`
* The previous step should start sshd; otherwise we can add a command to start it.
